version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PDF_GENERATOR: ${PDF_GENERATOR:-pdfkit}
      # Add other environment variables here, e.g.:
      # DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env.dev
    volumes:
      - .:/app # Mount the host directory to the container for live updates in dev
      - /app/node_modules # Exclude node_modules from the mount
    command: sh -c "mkdir -p /app/src/lib/data/receipt-pdfs && chmod -R 777 /app/src/lib/data && npm run dev"

profiles:
  - dev

---

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Fixed port for production
    environment:
      NODE_ENV: production
      PDF_GENERATOR: ${PDF_GENERATOR:-pdfkit}
      # Add other environment variables here, e.g.:
      # DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env.prod
    # No volume mount for code in production for this profile,
    # but PDF_DIR still needs to be writable if used.
    # Assuming Dockerfile copies src/lib/data and sets it up,
    # or if it's an external volume, it needs to be writable by the container user.
    # For consistency with the request to ensure writability and for cases where
    # src/lib/data might be part of the image build, we ensure it's writable.
    command: sh -c "mkdir -p /app/src/lib/data/receipt-pdfs && chmod -R 777 /app/src/lib/data && npm run start"

profiles:
  - prod
