export function ReceiptFooter() {
  return (
    <div className="text-center text-sm text-gray-600 border-t pt-4 mt-8" data-testid="receipt-footer">
      <p>Thank you for your business!</p>
      <p className="mt-2">Generated by Bakery Invoice Generator</p>
    </div>
  );
}
